name: File Watcher Integration Tests

on:
  push:
    branches: [ 'feature/container-file-watcher', 'feature/*file*watcher*' ]
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'Services/FileWatcherService.cs'
      - 'scripts/watch-container.*'
      - 'test-filewatcher.ps1'
      - '.github/workflows/file-watcher-tests.yml'

jobs:
  file-watcher-tests:
    name: File Watcher Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore DecompilerServer.sln
    
    - name: Build solution
      run: dotnet build DecompilerServer.sln --configuration Release --no-restore
    
    - name: Restore dependencies
      run: dotnet restore DecompilerServer.sln
    
    - name: Build all TestLibrary configurations
      run: |
        echo "Building all TestLibrary configurations..."
        dotnet build TestLibrary/TestLibrary.csproj --configuration Debug --no-restore
        dotnet build TestLibrary/TestLibrary.csproj --configuration FileWatcherTest --no-restore
        dotnet build TestLibrary/TestLibrary.csproj --configuration UnityDev --no-restore
        
    - name: Verify build outputs
      run: |
        echo "Verifying FileWatcherTest output..."
        ls -la test-assemblies/net8.0/ || echo "No test-assemblies directory"
        echo "Verifying UnityDev output..."  
        ls -la unity-assemblies/net8.0/ || echo "No unity-assemblies directory"
        echo "Verifying Debug output..."
        ls -la TestLibrary/bin/Debug/net8.0/ || echo "No Debug output"
    
    - name: Build Tests project
      run: dotnet build Tests/Tests.csproj --configuration Debug
    
    - name: Test FileWatcherService unit tests
      run: dotnet test Tests/Tests.csproj --configuration Debug --filter "ClassName~FileWatcher" --verbosity normal
    
    - name: Install Podman for container testing
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
    
    - name: Build container image for testing
      run: podman build -t localhost/decompiler-server:latest .
    
    - name: Test executable mode file watcher (FileWatcherTest config)
      run: |
        # Test with FileWatcherTest configuration (Assembly-CSharp.dll)
        mkdir -p /tmp/test-filewatcher
        cp test-assemblies/net8.0/Assembly-CSharp.dll /tmp/test-filewatcher/
        
        echo "Testing file watcher with FileWatcherTest configuration..."
        timeout 15s bash -c '
          dotnet run --project DecompilerServer.csproj -- --watch --assembly-path /tmp/test-filewatcher/Assembly-CSharp.dll &
          APP_PID=$!
          sleep 5
          echo "Simulating file change..."
          touch /tmp/test-filewatcher/Assembly-CSharp.dll
          sleep 5
          kill $APP_PID 2>/dev/null || true
          echo "FileWatcherTest configuration test completed"
        '
    
    - name: Test executable mode file watcher (UnityDev config)  
      run: |
        # Test with UnityDev configuration (Assembly-CSharp.dll)
        mkdir -p /tmp/test-unitydev
        cp unity-assemblies/net8.0/Assembly-CSharp.dll /tmp/test-unitydev/
        
        echo "Testing file watcher with UnityDev configuration..."
        timeout 15s bash -c '
          dotnet run --project DecompilerServer.csproj -- --watch --assembly-path /tmp/test-unitydev/Assembly-CSharp.dll &
          APP_PID=$!
          sleep 5
          echo "Simulating file change..."
          touch /tmp/test-unitydev/Assembly-CSharp.dll
          sleep 5  
          kill $APP_PID 2>/dev/null || true
          echo "UnityDev configuration test completed"
        '
    
    - name: Test container orchestration scripts (FileWatcherTest)
      run: |
        # Make scripts executable
        chmod +x scripts/watch-container.sh
        
        # Test with FileWatcherTest configuration
        mkdir -p /tmp/test-container-filewatcher  
        cp test-assemblies/net8.0/Assembly-CSharp.dll /tmp/test-container-filewatcher/
        
        echo "Testing container orchestration with FileWatcherTest config..."
        timeout 15s scripts/watch-container.sh /tmp/test-container-filewatcher/Assembly-CSharp.dll || true
        
    - name: Test container orchestration scripts (UnityDev)
      run: |
        # Test with UnityDev configuration  
        mkdir -p /tmp/test-container-unitydev
        cp unity-assemblies/net8.0/Assembly-CSharp.dll /tmp/test-container-unitydev/
        
        echo "Testing container orchestration with UnityDev config..."
        timeout 15s scripts/watch-container.sh /tmp/test-container-unitydev/Assembly-CSharp.dll || true
        
        echo "Container orchestration tests completed"
    
    - name: Validate build configuration differences
      run: |
        echo "=== Validating FileWatcherTest vs UnityDev differences ==="
        
        # Use strings command to check for compilation constants
        echo "FileWatcherTest build contains:"
        strings test-assemblies/net8.0/Assembly-CSharp.dll | grep -E "(FILEWATCHER|TEST)" || echo "No FILEWATCHER_TEST constants found"
        
        echo "UnityDev build contains:"  
        strings unity-assemblies/net8.0/Assembly-CSharp.dll | grep -E "(UNITY|DEV)" || echo "No UNITY_DEV_SIM constants found"
        
        # Compare file sizes (they should be different due to conditional compilation)
        FILEWATCHER_SIZE=$(stat -f%z test-assemblies/net8.0/Assembly-CSharp.dll 2>/dev/null || stat -c%s test-assemblies/net8.0/Assembly-CSharp.dll)
        UNITYDEV_SIZE=$(stat -f%z unity-assemblies/net8.0/Assembly-CSharp.dll 2>/dev/null || stat -c%s unity-assemblies/net8.0/Assembly-CSharp.dll)
        
        echo "FileWatcherTest size: $FILEWATCHER_SIZE bytes"
        echo "UnityDev size: $UNITYDEV_SIZE bytes"
        
        if [ "$FILEWATCHER_SIZE" != "$UNITYDEV_SIZE" ]; then
          echo "✅ Build configurations produce different outputs (conditional compilation working)"
        else
          echo "⚠️  Build configurations produce identical outputs (conditional compilation may not be working)"
        fi
    
    - name: Test PowerShell file watcher script (all configurations)
      run: |
        # Install PowerShell for comprehensive testing
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https software-properties-common
        wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
        
        echo "Testing FileWatcherTest configuration with PowerShell script..."
        pwsh -File test-filewatcher.ps1 -TestMode executable -BuildConfig FileWatcherTest -TestIterations 2 -SimulateChanges -VerboseOutput
        
        echo "Testing UnityDev configuration with PowerShell script..."  
        pwsh -File test-filewatcher.ps1 -TestMode executable -BuildConfig UnityDev -TestIterations 2 -SimulateChanges -VerboseOutput

  podman-compatibility:
    name: Podman Compatibility Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Restore dependencies
      run: dotnet restore DecompilerServer.sln
    
    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
    
    - name: Build with Podman
      run: podman build -t localhost/decompiler-server:latest .
    
    - name: Test Podman container startup
      run: |
        podman run --rm -d --name podman-test localhost/decompiler-server:latest
        sleep 5
        podman ps | grep podman-test
        podman stop podman-test || true